### PR TITLE
Issues/9

### LINKED ISSUE #9: Standardize djmarinara logs
Use the Python `logging` module to handle logs for djmarinara instead of `print` statements. Make those logs follow the principles of the 12 Factor App: https://12factor.net/

### PR DESCRIPTION
**Pull request by maseca**
Closes #9

### CODE REVIEW

**Comment by gorzek** [comment]
I'll put this through some testing tomorrow and then follow up!

**Comment by maseca** [comment]
BTW those format strings (f'{foo}') are a 3.6 feature. Figured you would be on at least 3.7

**Comment by gorzek** [comment]
Yeah, I never run lower than 3.6 these days so that's fine!

**Comment by gorzek** [comment]
Found a couple small issues but I won't let them hold up this PR.

I'm going to do a test deploy, and if that works OK I'll merge your PR then get my fixes in immediately after.

**Comment by gorzek** [comment]
OK, all good here. I do have a follow up issue to add as console logs no longer appear when djmarinara is running, nor is the log location clear.

**Comment by maseca** [comment]
I’m just using the basic config logger but it wouldn’t be hard to have it also stream to stdout. The log file location should maybe be configurable also

**Pull request merged**
